### ISSUE TITLE
Issuer is valid if value is either accounts.google.com or https://accounts.google.com

### ISSUE THREAD

**Issue by codemaster** [cheetah-games/jsonwebtoken-google#8]
Currently, `iss` is checked only for the value of "https://accounts.google.com". However, per Google's documentation, `iss` can be "accounts.google.com" or "https://accounts.google.com".

Ref: https://developers.google.com/identity/sign-in/web/backend-auth#verify-the-integrity-of-the-id-token

**Comment by avkviring** [comment]
fixed
